### ISSUE TITLE
Form 3 null ref exception

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-migration#3]
When trying to convert attached form 3 to EstNotice I get Null ref exception

[Form3.txt](https://github.com/Hankintailmoitukset/hilma-migration/files/3863617/Form3.txt)

Test method Hilma.Tests.FormTests.TestForm3 threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at Hilma.Domain.Integrations.General.SectionHelper.ValueTotal(ValueRangeContract totalValue, Boolean addPublicationAttribute) in C:\Git\hilma-migration\Hilma.Domain\Integrations\General\SectionHelper.cs:line 259
   at Hilma.Domain.Integrations.General.SectionHelper.ObjectContract() in C:\Git\hilma-migration\Hilma.Domain\Integrations\General\SectionHelper.cs:line 237
   at Hilma.Domain.Integrations.General.F03Factory.NoticeBody() in C:\Git\hilma-migration\Hilma.Domain\Integrations\General\F03Factory.cs:line 70
   at Hilma.Domain.Integrations.General.F03Factory.CreateForm() in C:\Git\hilma-migration\Hilma.Domain\Integrations\General\F03Factory.cs:line 52
   at Hilma.Domain.Integrations.TedNoticeFactory.CreateDocument() in C:\Git\hilma-migration\Hilma.Domain\Integrations\TedNoticeFactory.cs:line 87
   at Hilma.Domain.Validators.NoticeValidator.Validate(Boolean publishToTed, String& tedXml) in C:\Git\hilma-migration\Hilma.Domain\Validators\NoticeValidator.cs:line 90
   at Hilma.Tests.FormTests.TestForm(String formNumber) in C:\Git\hilma-migration\Hilma.Tests\FormTests.cs:line 50
   at Hilma.Tests.FormTests.TestForm3() in C:\Git\hilma-migration\Hilma.Tests\FormTests.cs:line 77

**Comment by tuomastolvanen** [comment]
This should be now fixed

**Comment by tuomastolvanen** [comment]
This is now fixed in the latest version
